name = "csharp"
title = "C#/.NET"
toc_landing_pages = [
  "/fundamentals/connection",
  "/fundamentals/crud",
  "/usage-examples",
]

intersphinx = [
  "https://www.mongodb.com/docs/manual/objects.inv",
  "https://www.mongodb.com/docs/drivers/objects.inv",
  "https://www.mongodb.com/docs/atlas/objects.inv",
]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
driver-long = "MongoDB .NET/C# Driver"
driver-short = ".NET/C# Driver"
lang-framework = ".NET/C#"
language = "C#"
docs-branch = "master"                                                                                                         # always set this to the docs branch (i.e. master, 1.7, 1.8, etc.)
version-number = "2.18"                                                                                                        # always set this to the driver branch (i.e. 1.7.0, 1.8.0, etc.)
version = "v{+version-number+}"
example = "https://raw.githubusercontent.com/mongodb/docs-csharp/{+docs-branch+}/source/includes/usage-examples/code-examples"
stable-api = "Stable API"
api-root = "https://mongodb.github.io/mongo-csharp-driver/{+version-number+}/apidocs/html"
bool-data-type = "``bool``"
string-data-type = "``str``"
int-data-type = "``int``"
not-available = "N/A"
