name = "csharp"
title = "C#/.NET"
eol = true
toc_landing_pages = [
    "/fundamentals/connection",
    "/fundamentals/crud",
    "/usage-examples",
    "/fundamentals",
    "/fundamentals/serialization",
]

intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/drivers/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv",
]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
driver-long = "MongoDB .NET/C# Driver"
driver-short = ".NET/C# Driver"
mdb-server = "MongoDB Server"
lang-framework = ".NET/C#"
framework = ".NET framework"
framework-version = "4.8"
standard-version = "2.1"
language = "C#"
mongo-community = "MongoDB Community Edition"
mongo-enterprise = "MongoDB Enterprise Edition"
docs-branch = "master"                                                                                          # always set this to the docs branch (i.e. master, 1.7, 1.8, etc.)
version-number = "2.21"                                                                                         # always set this to the driver branch (i.e. 1.7.0, 1.8.0, etc.)
version = "v{+version-number+}"
example = "https://raw.githubusercontent.com/mongodb/docs-csharp/{+docs-branch+}/source/includes/code-examples"
stable-api = "Stable API"
api-root = "https://mongodb.github.io/mongo-csharp-driver/{+version-number+}/apidocs/html"
bool-data-type = "``boolean``"
string-data-type = "``string``"
int-data-type = "``integer``"
not-available = "N/A"
analyzer = "MongoDB C# Analyzer"

[[banners]]
targets = ["*"]
variant = "info"
value = """\
    This version of the documentation is archived and no longer supported. View the `current documentation <https://www.mongodb.com/docs/drivers/csharp/current/>`__ to learn how to `upgrade your version of the {+driver-short+} <https://www.mongodb.com/docs/drivers/csharp/current/upgrade/>`__.\
    """
